from __future__ import annotations

import hashlib
import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .errors import ConfigError


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def read_json(path: Path) -> dict[str, Any]:
    return read_json_with_digest(path)[0]


def read_json_with_digest(path: Path) -> tuple[dict[str, Any], str]:
    """Parse and hash one file from a single byte read.

    Binding a review digest to a receipt must hash the exact bytes that were
    validated, so the parse and the digest come from the same read.
    """
    try:
        raw = path.read_bytes()
    except FileNotFoundError as exc:
        raise ConfigError(f"missing JSON file: {path}") from exc
    except OSError as exc:
        raise ConfigError(f"unreadable JSON file: {path}: {exc}") from exc
    digest = sha256_bytes(raw)
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ConfigError(f"JSON file is not valid UTF-8: {path}: {exc}") from exc
    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ConfigError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ConfigError(f"JSON root must be an object: {path}")
    return value, digest


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{uuid.uuid4().hex}")
    temporary.write_text(text, encoding="utf-8")
    os.replace(temporary, path)


def atomic_write_json(path: Path, value: object) -> None:
    atomic_write_text(path, json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n")


def canonical_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_text(value: str) -> str:
    return sha256_bytes(value.encode("utf-8"))


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def safe_relative(root: Path, relative_text: str) -> Path:
    relative = Path(relative_text)
    if relative.is_absolute() or not relative.parts or ".." in relative.parts:
        raise ConfigError(f"unsafe relative path: {relative_text!r}")
    root_resolved = root.resolve()
    resolved = (root / relative).resolve(strict=False)
    try:
        resolved.relative_to(root_resolved)
    except ValueError as exc:
        raise ConfigError(f"path escapes root: {relative_text!r}") from exc
    return resolved


def tree_digest(root: Path) -> str:
    if not root.exists():
        raise ConfigError(f"tree does not exist: {root}")
    digest = hashlib.sha256()
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix()):
        if ".git" in path.relative_to(root).parts:
            continue
        relative = path.relative_to(root).as_posix().encode("utf-8")
        if path.is_symlink():
            kind = b"symlink"
            payload = os.readlink(path).encode("utf-8")
        elif path.is_file():
            kind = b"executable" if path.stat().st_mode & 0o111 else b"file"
            payload = path.read_bytes()
        else:
            continue
        digest.update(kind + b"\0" + relative + b"\0")
        digest.update(len(payload).to_bytes(8, "big") + payload)
    return digest.hexdigest()


def content_light_artifacts(root: Path, names: list[str]) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for name in names:
        path = root / name
        if not path.is_file():
            continue
        result[name] = {
            "sha256": sha256_file(path),
            "bytes": path.stat().st_size,
        }
    return result


def python_source_digest(root: Path) -> str:
    """Hash canonical Python source without caches or generated bytecode."""
    digest = hashlib.sha256()
    paths = sorted(root.rglob("*.py"), key=lambda item: item.relative_to(root).as_posix())
    if not paths:
        raise ConfigError(f"no Python source found in {root}")
    for path in paths:
        if "__pycache__" in path.relative_to(root).parts:
            continue
        relative = path.relative_to(root).as_posix().encode("utf-8")
        payload = path.read_bytes()
        digest.update(b"python\0" + relative + b"\0")
        digest.update(len(payload).to_bytes(8, "big") + payload)
    return digest.hexdigest()
